model: HardMonotonicAttentionSeq2seq
embedding_size_src: 32
embedding_size_tgt: 32
hidden_size_src: 512
hidden_size_tgt: 512
num_layers_src: 2
num_layers_tgt: 2
dropout: 0.5

use_eos: true

epochs: 200
batch_size: 256

early_stopping_ratio: 1.5

experiment_dir: exps/hard_monotonic_attention
save_min_epoch: 5

toy_eval: [almával, megette, kutyát]
