model: HardMonotonicAttentionSeq2seq
embedding_size_src: 12
embedding_size_tgt: 12
hidden_size_src: 64
hidden_size_tgt: 64
num_layers_src: 1
num_layers_tgt: 1
dropout: 0.0

use_eos: true

epochs: 200
batch_size: 2

experiment_dir: exps/toy/hard_monotonic_attention
save_min_epoch: 5
