model: ReinflectionSeq2seq
dataset_class: ReinflectionDataset

lemma_embedding_size: 20
lemma_hidden_size: 128
lemma_num_layers: 3

tag_embedding_size: 10
tag_hidden_size: 64
tag_num_layers: 2

inflected_embedding_size: 30
inflected_hidden_size: 128
inflected_num_layers: 2

dropout: 0.2

use_eos: true

epochs: 200
batch_size: 128

early_stopping_ratio: 1.5

optimizer: Adam

experiment_dir: exps/sigmorphon_2018/hun_correct
save_min_epoch: 0
