model: SequenceClassifier
dataset_class: ClassificationDataset
embedding_size: 32
hidden_size: 1024
num_layers: 2
dropout: 0.2

epochs: 50
batch_size: 64

experiment_dir: exps/classification
save_min_epoch: 0
