model: TestPackedSeq2seq
dataset_class: InflectionDataset

embedding_size: 32
hidden_size: 512
num_layers: 2
dropout: 0.3

epochs: 200
batch_size: 128

optimizer: Adam

experiment_dir: exps/test_packed
save_min_epoch: 0
