model: LuongAttentionSeq2seq
embedding_size_src: 32
embedding_size_tgt: 32
hidden_size: 512
num_layers_src: 2
num_layers_tgt: 2
dropout: 0.0

use_eos: true

epochs: 200
batch_size: 128

optimizer: Adam

experiment_dir: exps/luong_attention
save_min_epoch: 20

early_stopping_window: 20
